LDAP {
  # Full DN of the admin user that can read the directory
  user = "cn=admin,dc=planetexpress,dc=com"

  # Password for the admin account
  password = "GoodNewsEveryone"

  # LDAP field that holds the user's login id
  userNameAttribute = "uid"

  # LDAP subtrees to search for users
  searchBase = [
    {organization = "", domainName = "ou=people,dc=planetexpress,dc=com"},
  ]

  context {
    # LDAP server URL — assumes docker setup (container_name = vinyldns-ldap)
    providerUrl = "ldap://localhost:19004"
    providerUrl = ${?LDAP_PROVIDER_URL}
  }
}

mysql {
  endpoint = "localhost:19002"
  endpoint = ${?MYSQL_ENDPOINT}

  settings {
    name = "vinyldns"
    name = ${?DATABASE_NAME}
    user = "root"
    user = ${?JDBC_USER}
    password = "pass"
    password = ${?JDBC_PASSWORD}
  }
}

api {
  port = 9000
  port = ${?API_PORT}
}

data-stores = ["mysql"]

# Must be true to manage shared zones through the portal
shared-display-enabled = true
shared-display-enabled = ${?SHARED_ZONES_ENABLED}

# You generate this yourself following https://www.playframework.com/documentation/2.7.x/ApplicationSecret
play.http.secret.key = "changeme"
play.http.secret.key = ${?PLAY_HTTP_SECRET_KEY}

# See https://www.playframework.com/documentation/2.8.x/AllowedHostsFilter for more details.
# Note: allowed = ["."] matches all hosts hence would not be recommended in a production environment.
play.filters.hosts {
  allowed = ["."]
}

# You can provide configuration overrides via local.conf if you don't want to replace everything in
# this configuration file
include "local.conf"

